rows: 5
cols: 5
initial_positions:
  -
    - 'R'
    - 'R'
    - 'R'
    - 'R'
    - 'R'
    - 'R'     # (0,5)
    - 'R'
    - 'R'
    - 'R'
    - 'R'
    - 'R'
    - 'R'     # (1,5)
    - 'R'
    - 'R'
    - 'R'
    - 'R'
    - 'R'
    - 'D'     # (2,5)
    - 'D'
    - 'D'
    - 'D'
    - 'D'
    - 'D'
    - 'D'     # (3,5)
    - 'D'
    - 'C'
    - 'C'
    - 'C'
    - 'C'
    - 'C'     # (4,5)
    - 'A'
    - 'A'
    - 'A'
    - 'A'
    - 'A'
    - 'A'     # (5,5)
  -