// This file is autogenerated. Changes will be overwritten.
#include "EWIEGA46WW/moc_celda.cpp"
#include "EWIEGA46WW/moc_construccion.cpp"
#include "EWIEGA46WW/moc_dialog_asignar_especia.cpp"
#include "EWIEGA46WW/moc_dialog_asignar_jugadoro.cpp"
#include "EWIEGA46WW/moc_dialog_cant_jugadores.cpp"
#include "EWIEGA46WW/moc_dialog_forma_tablero.cpp"
#include "EWIEGA46WW/moc_mainwindow.cpp"
